// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class ProdFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHuupj_lEkjvBNRVvMI_HZolLQCXCQ2Pg',
    appId: '1:439297986668:web:fcd722a5ca86ff10534849',
    messagingSenderId: '439297986668',
    projectId: 'app-nextbus',
    authDomain: 'app-nextbus.firebaseapp.com',
    storageBucket: 'app-nextbus.firebasestorage.app',
    measurementId: 'G-VYZTV2CKMM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx7mWptKwvoExhajm-5WwDgxsT3z9fq5E',
    appId: '1:439297986668:android:c02a4e9e28d89add534849',
    messagingSenderId: '439297986668',
    projectId: 'app-nextbus',
    storageBucket: 'app-nextbus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuZUpg3nW9XckHgSO01oM6fzVKnoJ6BPE',
    appId: '1:439297986668:ios:3464828250f17440534849',
    messagingSenderId: '439297986668',
    projectId: 'app-nextbus',
    storageBucket: 'app-nextbus.firebasestorage.app',
    androidClientId: '439297986668-lr0ol4ijg55d18utuckg274k78e4egol.apps.googleusercontent.com',
    iosClientId: '439297986668-v0isoa48flfc16drsaibhcsqb9nn0vug.apps.googleusercontent.com',
    iosBundleId: 'com.sourish.nextbus',
  );
}
