// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjFrlZiD-xPd7NRfgBe7W_75BRhXDJWeA',
    appId: '1:878462952161:web:0d724492919fd642400da0',
    messagingSenderId: '878462952161',
    projectId: 'next-bus-31103',
    authDomain: 'next-bus-31103.firebaseapp.com',
    storageBucket: 'next-bus-31103.firebasestorage.app',
    measurementId: 'G-B1XZ55EWQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhmxMFTSut-kIg76pXzsgH0jP9gx01NaA',
    appId: '1:878462952161:android:bc0fa23824749c32400da0',
    messagingSenderId: '878462952161',
    projectId: 'next-bus-31103',
    storageBucket: 'next-bus-31103.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1gauFzGetiPHW7uJ2ViwCiLuSeIHnojs',
    appId: '1:878462952161:ios:7058ef463a701c83400da0',
    messagingSenderId: '878462952161',
    projectId: 'next-bus-31103',
    storageBucket: 'next-bus-31103.firebasestorage.app',
    androidClientId: '878462952161-e3ak4ggputcmip5a27pfq7l0b8kj1v8j.apps.googleusercontent.com',
    iosClientId: '878462952161-hdtdc9bgqkg2m13futjffmikk1nehaek.apps.googleusercontent.com',
    iosBundleId: 'com.sourish.nextbus',
  );
}
