// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DevFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0_wAa0VCWsyU4KKE-AmXL5uVDEv_ZfQE',
    appId: '1:525382805804:web:032132e2936ce451f52489',
    messagingSenderId: '525382805804',
    projectId: 'next-bus-dev',
    authDomain: 'next-bus-dev.firebaseapp.com',
    storageBucket: 'next-bus-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT44nTDHTu26M7kjpJrRoZNW_ugvJjpsY',
    appId: '1:525382805804:android:28e3c934fe059f64f52489',
    messagingSenderId: '525382805804',
    projectId: 'next-bus-dev',
    storageBucket: 'next-bus-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ97rmf7IFtSptJ5zjtaquGqv1XAb5vKU',
    appId: '1:525382805804:ios:340619432b717f93f52489',
    messagingSenderId: '525382805804',
    projectId: 'next-bus-dev',
    storageBucket: 'next-bus-dev.firebasestorage.app',
    androidClientId: '525382805804-0cqj328385bgvgrh447le5ef8ej9qkrq.apps.googleusercontent.com',
    iosClientId: '525382805804-keo6nkkucts1m15afvbj854srur8kluo.apps.googleusercontent.com',
    iosBundleId: 'com.sourish.nextbus',
  );
}
